name: Continuous Deployment

on:
  release:
    types: [ published ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: deploy

    steps:
      - name: git checkout
        uses: actions/checkout@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v15

      - name: Cache nix container build output
        id: cache-nix-container
        uses: actions/cache@v3
        env:
          cache-name: cache-nix-container
        with:
          path: result
          key: ${{ runner.os }}-build-${{ env.cache-name }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}

      - name: Build Docker container using Nix
        run: nix build ".#docker"
        # Store the image in ./result

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: "${{ secrets.DOCKER_USERNAME }}"
          password: "${{ secrets.DOCKER_ACCESS_TOKEN }}"

      - name: Load and push image to Docker Hub
        run: |
          export IMAGE_TAG=$(docker load < result | grep -Po 'Loaded image: \K.*')
          export IMAGE_TAG_LATEST="$(echo "${IMAGE_TAG}" | cut -d ':' -f 1):latest"
          docker tag "${IMAGE_TAG}" "${IMAGE_TAG_LATEST}"
          docker push "${IMAGE_TAG}"
          docker push "${IMAGE_TAG_LATEST}"
