name: Continuous Integration (Nix)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  nix-ci:
    if: "!startsWith(github.event.head_commit.message, '[RELEASE]')"
    uses: christianharke/flake-commons/.github/workflows/nix-ci.yml@main
    with:
      branch: ${{ github.ref }}
      system: x86_64-linux

  nix-ci-arm:
    if: "!startsWith(github.event.head_commit.message, '[RELEASE]')"
    uses: christianharke/flake-commons/.github/workflows/nix-ci-arm.yml@main
    with:
      branch: ${{ github.ref }}
