name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  version:
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.PUSH_PAT }}
